robot_base_frame: base_link
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
obstacle_range: 3.0
#mark_threshold: 1
publish_voxel_map: true
footprint_padding: 0.0
navigation_map:
  map_topic: /map
obstacles:
  observation_sources: scan_main_m scan_main_c
  scan_main_m:
    topic: /scan_merged
    data_type: LaserScan
    clearing: false
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  scan_main_c:
    topic: /scan_merged
    data_type: LaserScan
    clearing: true
    marking: false
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
 